-- Generated automatically from whitelist/community.csv
-- Source of truth sync: upsert current emails, disable missing csv_sync ones

begin;

create temp table tmp_whitelist (
  email text primary key
) on commit drop;

insert into tmp_whitelist (email)
values
  ('2464alex@gmail.com'),
  ('52-2731175452424@zohomail.com'),
  ('a.chulanikova@gmail.com'),
  ('abrahamvillanueva.c@gmail.com'),
  ('adriancargua1314@gmail.com'),
  ('adrianseguradeorta@gmail.com'),
  ('adrivpardo@gmail.com'),
  ('aitorwoloszyn2010@gmail.com'),
  ('alan.rl1990@gmail.com'),
  ('albacanizares@usal.es'),
  ('albap1028@gmail.com'),
  ('albasolagea@gmail.com'),
  ('alexsofiacontent@gmail.com'),
  ('aleynymendez@gmail.com'),
  ('alfonsomaestrogarcia1998@gmail.com'),
  ('alfredaaip@gmail.com'),
  ('alvarotorres048@gmail.com'),
  ('amiratahiri04@gmail.com'),
  ('amnch73@gmail.com'),
  ('amontero_17@hotmail.com'),
  ('anavargiu@yahoo.com'),
  ('andersoncasrillo@gmail.com'),
  ('andresbetancur267@gmail.com'),
  ('andreymontano29@gmail.com'),
  ('angel_77001@hotmail.com'),
  ('anggel.abarca@gmail.com'),
  ('angiejimenez0816@gmail.com'),
  ('anowak79@icloud.com'),
  ('antonioguillamonmorales@gmail.com'),
  ('anzolafelipe93@gmail.com'),
  ('ariadnarodriguezbaratta@gmail.com'),
  ('arianna.idj@gmail.com'),
  ('ariel.03@hotmail.com'),
  ('arroyoalmayor@gmail.com'),
  ('aura.1999@hotmail.com'),
  ('aye161107@gmail.com'),
  ('beckerjoy12345@gmail.com'),
  ('belnuria8300@gmail.com'),
  ('bibianabeltran_5@hotmail.com'),
  ('bloomchi@gmail.com'),
  ('brayanmateus96@gmail.com'),
  ('camamen69@gmail.com'),
  ('camifse.2@gmail.com'),
  ('camilovila222@gmail.com'),
  ('carlos16andres07@gmail.com'),
  ('carlospelao1958@gmail.com'),
  ('carolinaa915@hotmail.com'),
  ('caronoa.ortiz@gmail.com'),
  ('casais243@gmail.com'),
  ('cggabrielaalban@yahoo.com'),
  ('charlie.antolin@gmail.com'),
  ('claudiadesantiago21@gmail.com'),
  ('claudiauseche3@gmail.com'),
  ('damiandimeglio0@gmail.com'),
  ('dan.mgonzalez@gmail.com'),
  ('dani2005r@gmail.com'),
  ('daniel.acostabarrios@gmail.com'),
  ('daniel.villarrealao@hotmail.com'),
  ('danieldelhoyo97@gmail.com'),
  ('danielriascos3004@gmail.com'),
  ('danieluigilt@gmail.com'),
  ('danorlandop@gmail.com'),
  ('davidantonio.saar@gmail.com'),
  ('daviniamuque@gmail.com'),
  ('deborahumch4@gmail.com'),
  ('deicygarcia427@gmail.com'),
  ('dicauryeroman@gmail.com'),
  ('diegotwich23@gmail.com'),
  ('doeddna@gmail.com'),
  ('dove_ca20@hotmail.com'),
  ('eleonora.garozzo@hotmail.it'),
  ('emileenn85@gmail.com'),
  ('endersondiaz19@gmail.com'),
  ('esquinaseo@gmail.com'),
  ('esteban.delaguilaa@gmail.com'),
  ('esthersarai777@gmail.com'),
  ('eve.leo91@gmail.com'),
  ('f.zamera@icloud.com'),
  ('fatimarodriguezmarquez@gmail.com'),
  ('fortaleza-divina.77@hotmail.fr'),
  ('freyderwork@gmail.com'),
  ('gabriela.vrd@gmail.com'),
  ('gabrieloop3@gmail.com'),
  ('gabrielperafanmunoz@gmail.com'),
  ('gabrielsbello@gmail.com'),
  ('gabyggp29@gmail.com'),
  ('gabytarira1998@gmail.com'),
  ('garciaeugenia868@gmail.com'),
  ('garenasoliver@gmail.com'),
  ('gdgb01@hotmail.com'),
  ('genemarhernandez@gmail.com'),
  ('georginasalazar007@gmail.com'),
  ('ginibethv@gmail.com'),
  ('gvrm1012@gmail.com'),
  ('gvsergio31@gmail.com'),
  ('hectorjjespinoza18@gmail.com'),
  ('ianjayt13@gmail.com'),
  ('idemarianomol@gmail.com'),
  ('imthechrisatyt@gmail.com'),
  ('ines100999@gmail.com'),
  ('inesvictoriawuzik@gmail.com'),
  ('infolucasacademy@gmail.com'),
  ('isavarelavi@gmail.com'),
  ('ivanlg1511@gmail.com'),
  ('ivanvlfromiel@gmail.com'),
  ('ivisolmancini@gmail.com'),
  ('ja.manrique10@uniandes.edu.co'),
  ('jacobmontiel222@gmail.com'),
  ('jagodablazx@gmail.com'),
  ('jaimechacon648@gmail.com'),
  ('javilucho68@gmail.com'),
  ('jdechaniz@gmail.com'),
  ('jen.nat.nut@gmail.com'),
  ('jespadaliberona@gmail.com'),
  ('jiro.vega@gmail.com'),
  ('joaquinf.gomezm@gmail.com'),
  ('joel.reichardt@icloud.com'),
  ('joelvilarrasacasas@gmail.com'),
  ('johnnyventura.julio@gmail.com'),
  ('joshuapaternina@gmail.com'),
  ('juan_noviembre@hotmail.com'),
  ('juancubillob@hotmail.com'),
  ('juanillo7_@hotmail.com'),
  ('juanmidelavega@hotmail.com'),
  ('juanpabloarco@yahoo.com'),
  ('karenzambrano020@gmail.com'),
  ('keevinjua@gmail.com'),
  ('kelly.grad.uff@gmail.com'),
  ('kerlyn.franco.parrales@hotmail.com'),
  ('l.alcayaga@gmail.com'),
  ('l.valoy2103@gmail.com'),
  ('laura.rcaso@gmail.com'),
  ('lauraandrea.martinezm@gmail.com'),
  ('lauramarcelafuentespacheco@gmail.com'),
  ('laurarlondon1027@gmail.com'),
  ('liliacherradidirigo@gmail.com'),
  ('lilianavergara70@hotmail.com'),
  ('lizbeth.lvdz@gmail.com'),
  ('luis.alejandro.gonzalez1996@gmail.com'),
  ('lukamoran.m@gmail.com'),
  ('lumaciasmo43@gmail.com'),
  ('madob86@gmail.com'),
  ('magoba2007@gmail.com'),
  ('maitebape21@gmail.com'),
  ('mariaencisopadial@gmail.com'),
  ('marielenasardi@gmail.com'),
  ('mariferbriseo@gmail.com'),
  ('marina.schroeder@sunrise.ch'),
  ('marinazulu18@gmail.com'),
  ('marionsul98@gmail.com'),
  ('mariuszmakiewicz1@gmail.com'),
  ('marpazpniewy23@gmail.com'),
  ('marteuge@hotmail.com'),
  ('mateojmartin@gmail.com'),
  ('mayrar4842@gmail.com'),
  ('mercanga@ymail.com'),
  ('mercyperezponce@gmail.com'),
  ('meysv.castillo@gmail.com'),
  ('miguel.sap89@gmail.com'),
  ('miguelalejandroramirez08@gmail.com'),
  ('monica@oemsupply.mx'),
  ('montesinokatherine@gmail.com'),
  ('mosheedgar@gmail.com'),
  ('muxuformacion@gmail.com'),
  ('nataliabgh@gmail.com'),
  ('nataly_orozco123@hotmail.com'),
  ('natamorales2120.a@gmail.com'),
  ('ncarbajalz88@gmail.com'),
  ('neir.1996.deathnote@gmail.com'),
  ('ngmarielaballesteros@gmail.com'),
  ('noa.delalamojimenez@gmail.com'),
  ('nordicjuan00@gmail.com'),
  ('oceane.melody.laforie@gmail.com'),
  ('ojeda.tobias@gmail.com'),
  ('orselli.nahuel@gmail.com'),
  ('oscarvzla11@gmail.com'),
  ('pablolluchva@gmail.com'),
  ('palaciosabriely@gmail.com'),
  ('panchoelcolombiano@gmail.com'),
  ('paolameregildo@gmail.com'),
  ('paulacamilatorresdaza@gmail.com'),
  ('paularm6591@gmail.com'),
  ('paulaserranoc@hotmail.com'),
  ('pena.claudia.fernanda@gmail.com'),
  ('pereiraleoncarolina@gmail.com'),
  ('priverovallado@gmail.com'),
  ('raquelgarciapuente@gmail.com'),
  ('raulinis1000@gmail.com'),
  ('raultercero333@gmail.com'),
  ('rcantero005@gmail.com'),
  ('reivermontoyac@gmail.com'),
  ('rensichiara0@gmail.com'),
  ('rocio.deyanira.mr@gmail.com'),
  ('rodriguezpasternackifelipe@gmail.com'),
  ('ron@ronelkins.us'),
  ('rosenineprovince@gmail.com'),
  ('rosi121019@gmail.com'),
  ('roxana.casillas.c@gmail.com'),
  ('rutsvieracastillo@gmail.com'),
  ('saltrias@gmail.com'),
  ('samantharubio1322@gmail.com'),
  ('sandner.katharina02@gmail.com'),
  ('santana15paula@gmail.com'),
  ('santyyw@gmail.com'),
  ('sbravosarango@gmail.com'),
  ('sepulvedapatricia498@gmail.com'),
  ('shadyakarawiname@yahoo.com'),
  ('shanireyes7@gmail.com'),
  ('silvinaliza@gmail.com'),
  ('smentadodev@gmail.com'),
  ('snops84@hotmail.com'),
  ('sofiiglesias02@gmail.com'),
  ('solange.martel.c@gmail.com'),
  ('solbejarano25@gmail.com'),
  ('soniafg82@hotmail.com'),
  ('sophiaferagottorojas@gmail.com'),
  ('soyunadibujante2.0@gmail.com'),
  ('taha.bezzaz@gmail.com'),
  ('todoesunproceso.profe@gmail.com'),
  ('torresluis597@hotmail.com'),
  ('trianacastroman@gmail.com'),
  ('trujillocalebjosue@gmail.com'),
  ('v.andriossi@gmail.com'),
  ('varnerferrato@gmail.com'),
  ('victoralonbla1@gmail.com'),
  ('violaine.garcia01@icloud.com'),
  ('vipaqui29@gmail.com'),
  ('willbergomez0@gmail.com'),
  ('xsyhobx@gmail.com'),
  ('y.ghdez@gmail.com'),
  ('yazmingonzalezelizarraraz@gmail.com'),
  ('yoselinnolasco73@gmail.com'),
  ('yrobleto26@gmail.com'),
  ('zeron.orlando@gmail.com');

insert into public.auth_whitelist (email, can_register, can_login, source, last_synced_at)
select t.email, true, true, 'csv_sync', now()
from tmp_whitelist t
on conflict (email) do update set
  can_register = excluded.can_register,
  can_login = excluded.can_login,
  source = excluded.source,
  last_synced_at = excluded.last_synced_at
where public.auth_whitelist.source = 'csv_sync';

update public.auth_whitelist w
set
  can_register = false,
  can_login = false,
  last_synced_at = now()
where not exists (
  select 1
  from tmp_whitelist t
  where t.email = w.email
)
and w.source = 'csv_sync';

commit;
