-- Generated automatically from whitelist/community.csv
-- Source of truth sync: upsert current emails, disable missing ones

begin;

create temp table tmp_whitelist (
  email text primary key
) on commit drop;

insert into tmp_whitelist (email)
values
  ('2464alex@gmail.com'),
  ('a.altamiranoc97@gmail.com'),
  ('a.chulanikova@gmail.com'),
  ('abrahamvillanueva.c@gmail.com'),
  ('adriancargua1314@gmail.com'),
  ('adrianseguradeorta@gmail.com'),
  ('aitorwoloszyn2010@gmail.com'),
  ('alan.rl1990@gmail.com'),
  ('albacanizares@usal.es'),
  ('albap1028@gmail.com'),
  ('albasolagea@gmail.com'),
  ('alfarojimena082@gmail.com'),
  ('alfonsomaestrogarcia1998@gmail.com'),
  ('alfredaaip@gmail.com'),
  ('alvarotorres048@gmail.com'),
  ('alvarovillanueva207@gmail.com'),
  ('amiratahiri04@gmail.com'),
  ('amontero_17@hotmail.com'),
  ('amvv.abogada@gmail.com'),
  ('andersoncasrillo@gmail.com'),
  ('andresbetancur267@gmail.com'),
  ('angel_77001@hotmail.com'),
  ('anggel.abarca@gmail.com'),
  ('angiejimenez0816@gmail.com'),
  ('angiesantamaria151@gmail.com'),
  ('anowak79@icloud.com'),
  ('antonioguillamonmorales@gmail.com'),
  ('ariadnarodriguezbaratta@gmail.com'),
  ('arianna.idj@gmail.com'),
  ('ariel.03@hotmail.com'),
  ('aura.1999@hotmail.com'),
  ('aye161107@gmail.com'),
  ('beckerjoy12345@gmail.com'),
  ('belnuria8300@gmail.com'),
  ('bibianabeltran_5@hotmail.com'),
  ('bloomchi@gmail.com'),
  ('brayanmateus96@gmail.com'),
  ('camamen69@gmail.com'),
  ('camifse.2@gmail.com'),
  ('camilovila222@gmail.com'),
  ('carlospelao1958@gmail.com'),
  ('carlotttadsg@gmail.com'),
  ('casais243@gmail.com'),
  ('cggabrielaalban@yahoo.com'),
  ('charlie.antolin@gmail.com'),
  ('daniel.villarrealao@hotmail.com'),
  ('danieldelhoyo97@gmail.com'),
  ('danielriascos3004@gmail.com'),
  ('danieluigilt@gmail.com'),
  ('danorlandop@gmail.com'),
  ('davidantonio.saar@gmail.com'),
  ('daviniamuque@gmail.com'),
  ('deicygarcia427@gmail.com'),
  ('diegotwich23@gmail.com'),
  ('dove_ca20@hotmail.com'),
  ('eleonora.garozzo@hotmail.it'),
  ('endersondiaz19@gmail.com'),
  ('esteban.delaguilaa@gmail.com'),
  ('esthersarai777@gmail.com'),
  ('eve.leo91@gmail.com'),
  ('f.zamera@icloud.com'),
  ('fatimarodriguezmarquez@gmail.com'),
  ('federico.romaniello15@gmail.com'),
  ('gabriela.vrd@gmail.com'),
  ('gabrielperafanmunoz@gmail.com'),
  ('gabrielsbello@gmail.com'),
  ('gdgb01@hotmail.com'),
  ('genemarhernandez@gmail.com'),
  ('georginasalazar007@gmail.com'),
  ('gvrm1012@gmail.com'),
  ('gvsergio31@gmail.com'),
  ('ianjayt13@gmail.com'),
  ('idemarianomol@gmail.com'),
  ('imthechrisatyt@gmail.com'),
  ('ines100999@gmail.com'),
  ('inesvictoriawuzik@gmail.com'),
  ('infolucasacademy@gmail.com'),
  ('isavarelavi@gmail.com'),
  ('ivanlg1511@gmail.com'),
  ('ivisolmancini@gmail.com'),
  ('ja.manrique10@uniandes.edu.co'),
  ('jacobmontiel222@gmail.com'),
  ('jagodablazx@gmail.com'),
  ('jaimechacon648@gmail.com'),
  ('jdechaniz@gmail.com'),
  ('jen.nat.nut@gmail.com'),
  ('jiro.vega@gmail.com'),
  ('joaquinf.gomezm@gmail.com'),
  ('joelvilarrasacasas@gmail.com'),
  ('joshuapaternina@gmail.com'),
  ('juan_noviembre@hotmail.com'),
  ('juancubillob@hotmail.com'),
  ('juanillo7_@hotmail.com'),
  ('juanmidelavega@hotmail.com'),
  ('juanpabloarco@yahoo.com'),
  ('karenzambrano020@gmail.com'),
  ('keevinjua@gmail.com'),
  ('kerlyn.franco.parrales@hotmail.com'),
  ('l.alcayaga@gmail.com'),
  ('l.bruno17@gmail.com'),
  ('l.valoy2103@gmail.com'),
  ('laurarlondon1027@gmail.com'),
  ('lumaciasmo43@gmail.com'),
  ('madob86@gmail.com'),
  ('magoba2007@gmail.com'),
  ('mariaencisopadial@gmail.com'),
  ('marielenasardi@gmail.com'),
  ('mariferbriseo@gmail.com'),
  ('marina.schroeder@sunrise.ch'),
  ('marionsul98@gmail.com'),
  ('mariuszmakiewicz1@gmail.com'),
  ('marteuge@hotmail.com'),
  ('mateojmartin@gmail.com'),
  ('mayrar4842@gmail.com'),
  ('mercanga@ymail.com'),
  ('meysv.castillo@gmail.com'),
  ('miguel.sap89@gmail.com'),
  ('miguelalejandroramirez08@gmail.com'),
  ('montesinokatherine@gmail.com'),
  ('mosheedgar@gmail.com'),
  ('nataliabgh@gmail.com'),
  ('nataly_orozco123@hotmail.com'),
  ('natamorales2120.a@gmail.com'),
  ('nazaretmonteroperalta@gmail.com'),
  ('neir.1996.deathnote@gmail.com'),
  ('ngmarielaballesteros@gmail.com'),
  ('ojeda.tobias@gmail.com'),
  ('orselli.nahuel@gmail.com'),
  ('pablolluchva@gmail.com'),
  ('paolameregildo@gmail.com'),
  ('paoloniornella@gmail.com'),
  ('paularm6591@gmail.com'),
  ('paulaserranoc@hotmail.com'),
  ('priverovallado@gmail.com'),
  ('raquelgarciapuente@gmail.com'),
  ('raulinis1000@gmail.com'),
  ('raultercero333@gmail.com'),
  ('rcantero005@gmail.com'),
  ('rensichiara0@gmail.com'),
  ('rocio.deyanira.mr@gmail.com'),
  ('roxana.casillas.c@gmail.com'),
  ('samantharubio1322@gmail.com'),
  ('sandner.katharina02@gmail.com'),
  ('santana15paula@gmail.com'),
  ('santyyw@gmail.com'),
  ('sbravosarango@gmail.com'),
  ('sepulvedapatricia498@gmail.com'),
  ('shadyakarawiname@yahoo.com'),
  ('shanireyes7@gmail.com'),
  ('silvinaliza@gmail.com'),
  ('snops84@hotmail.com'),
  ('sofiiglesias02@gmail.com'),
  ('solange.martel.c@gmail.com'),
  ('solbejarano25@gmail.com'),
  ('sophiaferagottorojas@gmail.com'),
  ('soyunadibujante2.0@gmail.com'),
  ('taha.bezzaz@gmail.com'),
  ('todoesunproceso.profe@gmail.com'),
  ('trujillocalebjosue@gmail.com'),
  ('v.andriossi@gmail.com'),
  ('varnerferrato@gmail.com'),
  ('victoralonbla1@gmail.com'),
  ('violaine.garcia01@icloud.com'),
  ('willbergomez0@gmail.com'),
  ('xsyhobx@gmail.com'),
  ('y.ghdez@gmail.com'),
  ('yoselinnolasco73@gmail.com'),
  ('zeron.orlando@gmail.com');

insert into public.auth_whitelist (email, can_register, can_login, source, last_synced_at)
select t.email, true, true, 'csv_sync', now()
from tmp_whitelist t
on conflict (email) do update set
  can_register = excluded.can_register,
  can_login = excluded.can_login,
  source = excluded.source,
  last_synced_at = excluded.last_synced_at;

update public.auth_whitelist w
set
  can_register = false,
  can_login = false,
  source = 'csv_sync',
  last_synced_at = now()
where not exists (
  select 1
  from tmp_whitelist t
  where t.email = w.email
);

commit;
