// PREMIUM VOICE (Luis, 6 Oct): Gemini TTS for development and production.
//
// Same behaviour as the local plugin (scripts/vite-premium-voice.mjs):
//   POST { text, lang } -> audio/wav, generated by Gemini (gemini-3.8-flash-lite-tts, voice Kore).
//   Each text is generated once and saved in the private "premium-tts" bucket for everyone, so
//   playing it again costs nothing.
// Secrets: GEMINI_API_KEY (required; without it the function answers 404 and the app keeps its old
// voices), GEMINI_TTS_MODEL, GEMINI_TTS_VOICE and PREMIUM_TTS_DAILY_LIMIT (optional).
// Every audio adds to public.premium_tts_daily_usage (migration 20261006130000), which the admin
// panel reads and which caps how many new audios one student can create per day.
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { CORS_HEADERS, jsonResponse } from '../_shared/http.ts'

const DEFAULT_MODEL = 'gemini-3.8-flash-lite-tts'
const DEFAULT_VOICE = 'Kore'
const DEFAULT_DAILY_LIMIT = 300
const MAX_TEXT_CHARS = 600
const BUCKET = 'premium-tts'
const LANG_PATTERN = /^[a-z]{2,3}(-[A-Z]{2})?$/

// Paid tier prices per million tokens (ai.google.dev/gemini-api/docs/pricing, October 2026);
// they double from 1 January 2027. Same table as the local plugin.
const PRICES: Record<string, { input: [number, number]; output: [number, number] }> = {
  'gemini-3.8-flash-lite-tts': { input: [0.5, 1], output: [6, 12] },
  'gemini-3.8-flash-tts': { input: [0.5, 1], output: [9, 18] },
}
const PRICE_CHANGE_DAY = '2027-01-01'
/** Gemini counts 25 audio tokens per second when the answer does not say. */
const AUDIO_TOKENS_PER_SECOND = 25

type Bytes = Uint8Array<ArrayBuffer>
type DbError = { message: string } | null

/** Only what this function uses of the service-role client (same approach as pronunciation-cache.ts). */
type AdminClient = {
  rpc: (fn: string, args: Record<string, unknown>) => PromiseLike<{ data: unknown; error: DbError }>
  from: (table: string) => {
    select: (columns: string) => {
      eq: (column: string, value: string) => {
        eq: (column: string, value: string) => PromiseLike<{ data: unknown; error: DbError }>
      }
    }
  }
  storage: {
    from: (bucket: string) => {
      download: (path: string) => PromiseLike<{ data: Blob | null; error: DbError }>
      upload: (
        path: string,
        body: Bytes,
        options: { contentType: string; upsert: boolean },
      ) => PromiseLike<{ error: DbError }>
    }
  }
}

function audioResponse(audio: Bytes): Response {
  return new Response(audio, {
    status: 200,
    headers: {
      ...CORS_HEADERS,
      'Content-Type': 'audio/wav',
      'Cache-Control': 'private, max-age=86400',
    },
  })
}

async function requireUserId(req: Request): Promise<string | null> {
  const authHeader = req.headers.get('Authorization')
  const supabaseUrl = Deno.env.get('SUPABASE_URL')
  const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY')
  if (!authHeader || !supabaseUrl || !supabaseAnonKey) return null
  const client = createClient(supabaseUrl, supabaseAnonKey, {
    global: { headers: { Authorization: authHeader } },
  })
  const { data, error } = await client.auth.getUser()
  if (error || !data.user) return null
  return data.user.id
}

function createAdminClient(): AdminClient | null {
  const supabaseUrl = Deno.env.get('SUPABASE_URL')
  const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')
  if (!supabaseUrl || !serviceRoleKey) return null
  return createClient(supabaseUrl, serviceRoleKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  }) as unknown as AdminClient
}

async function sha1Hex(value: string): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-1', new TextEncoder().encode(value))
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('')
}

function base64ToBytes(value: string): Bytes {
  const binary = atob(value)
  const bytes = new Uint8Array(binary.length)
  for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index)
  return bytes
}

function isWav(bytes: Uint8Array): boolean {
  return bytes.length >= 44 && String.fromCharCode(...bytes.subarray(0, 4)) === 'RIFF'
}

/** Gemini answers raw 16-bit mono PCM: wrap it in a WAV header so every browser can play it. */
function pcmToWav(pcm: Bytes, rate: number): Bytes {
  const wav = new Uint8Array(44 + pcm.length)
  const view = new DataView(wav.buffer)
  const writeAscii = (offset: number, text: string) => {
    for (let index = 0; index < text.length; index += 1) wav[offset + index] = text.charCodeAt(index)
  }
  writeAscii(0, 'RIFF')
  view.setUint32(4, 36 + pcm.length, true)
  writeAscii(8, 'WAVE')
  writeAscii(12, 'fmt ')
  view.setUint32(16, 16, true)
  view.setUint16(20, 1, true)
  view.setUint16(22, 1, true)
  view.setUint32(24, rate, true)
  view.setUint32(28, rate * 2, true)
  view.setUint16(32, 2, true)
  view.setUint16(34, 16, true)
  writeAscii(36, 'data')
  view.setUint32(40, pcm.length, true)
  wav.set(pcm, 44)
  return wav
}

function wavSeconds(wav: Uint8Array): number {
  if (!isWav(wav)) return 0
  const byteRate = new DataView(wav.buffer, wav.byteOffset, wav.byteLength).getUint32(28, true) || 48000
  return Math.max(0, (wav.length - 44) / byteRate)
}

function priceUsd(model: string, inputTokens: number, outputTokens: number): number {
  const prices = PRICES[model] || PRICES[DEFAULT_MODEL]
  const day = new Date().toISOString().slice(0, 10)
  const step = day >= PRICE_CHANGE_DAY ? 1 : 0
  return (inputTokens * prices.input[step] + outputTokens * prices.output[step]) / 1_000_000
}

type Generated = { audio: Bytes; seconds: number; inputTokens: number; outputTokens: number }

async function generateWithGemini(
  apiKey: string,
  model: string,
  voice: string,
  text: string,
  lang: string,
): Promise<Generated> {
  const languageName = new Intl.DisplayNames(['en'], { type: 'language' }).of(lang) || lang
  const call = async (withStyle: boolean) => {
    const part: Record<string, unknown> = { text }
    if (withStyle) {
      part.speech_metadata = {
        style: `Native ${languageName} speaker (${lang}). Read it in ${languageName}, clearly and naturally, like a friendly teacher.`,
      }
    }
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'x-goog-api-key': apiKey },
        body: JSON.stringify({
          contents: [{ role: 'user', parts: [part] }],
          generationConfig: { responseModalities: ['AUDIO'], speechConfig: { voiceConfig: { voice } } },
        }),
      },
    )
    const data = await response.json().catch(() => ({}))
    return { response, data }
  }

  let { response, data } = await call(true)
  // If this model does not accept the style field, try once with the plain text.
  if (response.status === 400) ({ response, data } = await call(false))
  if (!response.ok) throw new Error(`Gemini TTS ${response.status}`)

  const parts = data?.candidates?.[0]?.content?.parts || []
  const inline = parts.find((part: { inlineData?: { data?: string } }) => part?.inlineData?.data)?.inlineData
  if (!inline?.data) throw new Error('Gemini TTS: no audio in the answer')
  const bytes = base64ToBytes(inline.data)
  const rate = Number(/rate=(\d+)/.exec(inline.mimeType || '')?.[1]) || 24000
  const audio = isWav(bytes) ? bytes : pcmToWav(bytes, rate)
  const seconds = wavSeconds(audio)
  const meta = data?.usageMetadata || {}
  return {
    audio,
    seconds,
    inputTokens: Number(meta.promptTokenCount) || Math.ceil((text.length + 120) / 4),
    outputTokens: Number(meta.candidatesTokenCount) || Math.ceil(seconds * AUDIO_TOKENS_PER_SECOND),
  }
}

async function track(
  admin: AdminClient,
  userId: string,
  model: string,
  generated: Generated | null,
): Promise<number | null> {
  const { data, error } = await admin.rpc('premium_tts_track', {
    p_user_id: userId,
    p_model: model,
    p_generated: Boolean(generated),
    p_seconds: generated ? Math.round(generated.seconds * 100) / 100 : 0,
    p_input_tokens: generated?.inputTokens ?? 0,
    p_output_tokens: generated?.outputTokens ?? 0,
    p_cost_usd: generated ? priceUsd(model, generated.inputTokens, generated.outputTokens) : 0,
  })
  if (error) {
    console.warn('premium-tts: usage not saved', error.message)
    return null
  }
  return typeof data === 'number' ? data : null
}

async function generatedToday(admin: AdminClient, userId: string): Promise<number> {
  const day = new Date().toISOString().slice(0, 10)
  const { data, error } = await admin
    .from('premium_tts_daily_usage')
    .select('generated')
    .eq('day', day)
    .eq('user_id', userId)
  if (error || !Array.isArray(data)) return 0
  return data.reduce((sum, row) => sum + (Number((row as { generated?: number }).generated) || 0), 0)
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS_HEADERS })
  if (req.method !== 'POST') return jsonResponse(405, { error: 'Method not allowed' })

  // No key = premium voice off: 404 tells the app to stop asking and use its old voices.
  const apiKey = Deno.env.get('GEMINI_API_KEY') || ''
  if (!apiKey) return jsonResponse(404, { error: 'Premium voice is off' })

  const userId = await requireUserId(req)
  if (!userId) return jsonResponse(401, { error: 'Unauthorized' })

  let text = ''
  let lang = ''
  try {
    const body = await req.json()
    text = String(body?.text ?? '').trim()
    lang = String(body?.lang ?? '')
  } catch {
    return jsonResponse(400, { error: 'Invalid JSON body' })
  }
  if (!text || text.length > MAX_TEXT_CHARS || !LANG_PATTERN.test(lang)) {
    return jsonResponse(400, { error: 'Bad request' })
  }

  const admin = createAdminClient()
  if (!admin) return jsonResponse(500, { error: 'Supabase function environment is not configured' })

  const model = Deno.env.get('GEMINI_TTS_MODEL') || DEFAULT_MODEL
  const voice = Deno.env.get('GEMINI_TTS_VOICE') || DEFAULT_VOICE
  const dailyLimit = Number(Deno.env.get('PREMIUM_TTS_DAILY_LIMIT')) || DEFAULT_DAILY_LIMIT
  const key = await sha1Hex(`${model}|${voice}|${lang}|${text}`)
  const path = `${model}/${voice}/${key}.wav`

  // Already generated by anyone: free.
  const cached = await admin.storage.from(BUCKET).download(path)
  if (!cached.error && cached.data) {
    await track(admin, userId, model, null)
    return audioResponse(new Uint8Array(await cached.data.arrayBuffer()))
  }

  // Cost guard: a student cannot create more than PREMIUM_TTS_DAILY_LIMIT new audios a day.
  // Over it the app falls back to its old voices for the rest of the day.
  if ((await generatedToday(admin, userId)) >= dailyLimit) {
    return jsonResponse(429, { error: 'Daily premium voice limit reached' })
  }

  try {
    const generated = await generateWithGemini(apiKey, model, voice, text, lang)
    const upload = await admin.storage.from(BUCKET).upload(path, generated.audio, {
      contentType: 'audio/wav',
      upsert: true,
    })
    if (upload.error) console.warn('premium-tts: audio not cached', upload.error.message)
    await track(admin, userId, model, generated)
    return audioResponse(generated.audio)
  } catch (error) {
    console.warn('premium-tts failed', error instanceof Error ? error.message : String(error))
    return jsonResponse(502, { error: 'Premium voice failed' })
  }
})
